### ISSUE TITLE
How to run Hubsort and Hubclustering separated from apps?

### ISSUE THREAD

**Issue by geo-roc** [CMUAbstract/Graph-Reordering-IISWC18#3]
The code in Ligra/ligra-hubsort/ can be compiled and run with ligra-formated graph.
I can not get the reordered graph from apps.
Would you please give a simple version of Hubsort and Hubclustering which can take plain edges file as input and output edges after reordering?
For example, input plain edges file 
`14 10`
`2 19` 
`14 1`
`...`
after reordering(Hubsort and Hubclustering)
output the edges file with same format as input.

**Comment by bvignesh** [comment]
I have created a tool that should allow you to output an edgelist of a degree-sorted, hub-sorted, or hub-clustered graph.

You can find information in the main README.md 

Please re-open this issue if you find any bugs in the new tool or were looking for a different feature

**Comment by geo-roc** [comment]
Thanks a lot for your help.
So far, I can compile the graph-reorderer.cc in GAP/Degsort, GAP/HubCluster, GAP/HubSort with command "make graph-reorderer".
I then run command "./graph-reorderer -f 51083.txt -e out.txt" and 
I get stuck with the error message "Unrecognized suffix: .txt".
The problem is the input file format is not clear and I didn't find a demo input file in GAP/ folder.
Would you please add a demo edge list file as input to test the algorithms?

**Comment by geo-roc** [comment]
I got it! 
I just changed the file name 51083.txt to 51083.el and successfully run the code.
GAP require the input file end with .el 
Really appriciate your support!
